language: node_js

node_js:
  - 6
  - 8

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn ci

notifications:
  email: false

cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"
